export enum Sound {
  BattleMusic = 'battle-music',
  Coins = 'coins',
  CaveMusic = 'cave-music',
  EnemyAttacks = 'enemy-attacks',
  FieldMusic = 'field-music',
  Heal = 'heal',
  Ice = 'ice',
  LevelUp = 'level-up',
  PartyDestroyed = 'party-destroyed',
  PlayerAttacks = 'player-attacks',
  Talking = 'talking',
  TownMusic = 'town-music',
  Warp = 'warp',
}
